env:
  global:
    - CC_TEST_REPORTER_ID=3cd3f4810dc2d510557d2100005fd5e5497683d44f7f56b6fcd1633c3335f46b
language: python
python:
  - 3.4
  - 3.5
  - 3.6
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
 - flake8
 - pytest --cov=pymfy --cov-report xml
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - pip install codecov
  - codecov
deploy:
  - provider: pypi
    user: tetienne
    password:
      secure: Y14WBjQIHQO+uWwLGX6zeYqJv3zyJ1WKyG0KdPLUrL8zMFeaIf+78HPNRawZpVPkhzxEbcPJY1LXsti1663HxCwQB2xdShkU09T3mjn8uQOvdvplYa52valqpfFPcXIHz6S1xX6XUKa5z+8e/YK2Dujo4laiXrdbpuOAXVU+tdJjQMaYgtrFbQIXG8YcybdQ03Um9qOLFTgv1P2qW1EG0DaTrq/egSQwFNNABlpIITIIyExSJRIOf/aAAAGNyE0WLzuSPA686pXAIy5vuvDgBSFQ1V4xzUUi8i7DLQ4aadXul9VXdLJqTAKshBxRqrkuMSgy74NC9mI/z/rTA+O5a8vWNWo0ufn2av8HDH25JYOSJi8hKTDlMcg9fiw5uq6KpLQwmE9SPFG0RITZUpfuCQN9ZXqu5deBE8+LcvPkrPkw6RYpQqXJXgQEdawuo/MyBrB6GUvPSn5AQAprwhOjVxzhcQiYIWStqgEaQV41O+2q6vM7vB7lyZ3fsIEh7RUIYvp+tJUwm14I64Mkxxyg74uBMfNGiZSRW7WZGkLp4suc5tivq27piYbRKggvwrYkz9iSoXSghTHwMcDu1Jyxy4slWtIK4jNOh/onInobAkI2hR0LcqX3te+GBngCcvHkhhDiRXtqE/DWDNDixlOkLHrQ1FtsmY/xnwzK72lO+Ic=
    distributions: "sdist bdist_wheel"
    skip_existing: true
    on:
      tags: true
